export enum UserRole {
  USER = 'USER',
  COMPANION = 'COMPANION',
  ADMIN = 'ADMIN',
}

export enum CompanionType {
  STANDARD = 'STANDARD',
  VERIFIED = 'VERIFIED',
  EXPERT = 'EXPERT',
}

export enum CompanionStatus {
  PENDING_REVIEW = 'PENDING_REVIEW',
  APPROVED = 'APPROVED',
  SUSPENDED = 'SUSPENDED',
  DEACTIVATED = 'DEACTIVATED',
}

export enum SessionType {
  FOCUS = 'FOCUS',
  DECISION = 'DECISION',
  EMOTIONAL_UNLOAD = 'EMOTIONAL_UNLOAD',
  PLANNING = 'PLANNING',
}

export enum SessionStatus {
  PENDING_MATCH = 'PENDING_MATCH',
  MATCHED = 'MATCHED',
  PAYMENT_AUTHORIZED = 'PAYMENT_AUTHORIZED',
  READY = 'READY',
  IN_PROGRESS = 'IN_PROGRESS',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  ABANDONED = 'ABANDONED',
  DISPUTED = 'DISPUTED',
}

export enum ContractMode {
  STRICT = 'STRICT',
  MODERATE = 'MODERATE',
  FLEXIBLE = 'FLEXIBLE',
}

export enum DriftSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  AUTHORIZED = 'AUTHORIZED',
  CAPTURED = 'CAPTURED',
  REFUNDED = 'REFUNDED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum RefundReason {
  TECHNICAL_FAILURE = 'TECHNICAL_FAILURE',
  COMPANION_NO_SHOW = 'COMPANION_NO_SHOW',
  ADMIN_OVERRIDE = 'ADMIN_OVERRIDE',
}

export enum AvailabilityDay {
  MONDAY = 'MONDAY',
  TUESDAY = 'TUESDAY',
  WEDNESDAY = 'WEDNESDAY',
  THURSDAY = 'THURSDAY',
  FRIDAY = 'FRIDAY',
  SATURDAY = 'SATURDAY',
  SUNDAY = 'SUNDAY',
}

export enum AuditAction {
  USER_REGISTER = 'USER_REGISTER',
  USER_LOGIN = 'USER_LOGIN',
  USER_DELETE = 'USER_DELETE',
  SESSION_CREATE = 'SESSION_CREATE',
  SESSION_START = 'SESSION_START',
  SESSION_END = 'SESSION_END',
  PAYMENT_AUTHORIZE = 'PAYMENT_AUTHORIZE',
  PAYMENT_CAPTURE = 'PAYMENT_CAPTURE',
  PAYMENT_REFUND = 'PAYMENT_REFUND',
  COMPANION_APPROVE = 'COMPANION_APPROVE',
  COMPANION_SUSPEND = 'COMPANION_SUSPEND',
  ADMIN_ACTION = 'ADMIN_ACTION',
  DATA_EXPORT = 'DATA_EXPORT',
  DATA_DELETION = 'DATA_DELETION',
}
